routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/', 'HomeController');
Route::get('plumbing', function () {
    return view('plumbing');
});

Route::get('service/{service?}', 'HomeController@SelectService')->name('service.select');
Route::get('cart/{category}', 'HomeController@category');

Route::get('plumbing4/{service}/{category}', 'HomeController@service');
Route::get('plumbing5/{item_mapping_id}', 'HomeController@itemtype');
Route::get('plumbing6/{itemTypeId}', 'HomeController@item');
//Route::get('summary/{cart_id}', 'HomeController@summary')->name('order.summary');
//Route::get('confirm/{cart_id}', 'HomeController@confirm')->name('order.confirm');
Route::get('account', 'HomeController@account');
Route::get('security', 'HomeController@security');
Route::resource('accountupdate', 'AccountController');





Route::get('/logout', 'Auth\LoginController@logout');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::post('/proceed', 'HomeController@proceedTransaction')->name('proceed.transaction');


Route::get('user/data/{cart}', 'HomeController@OrderAddress')->name('cart.user')->middleware('auth');
Route::post('user/data', 'HomeController@submitOrderAddress')->name('address.submit')->middleware('auth');
Route::get('summary/{cart}', 'HomeController@orderSummary')->name('order.summary')->middleware('auth');
Route::post('confirm', 'HomeController@confirmOrder')->name('order.confirm')->middleware('auth');
Route::post('confirm/{cart}', 'HomeController@submitConfirmOrder')->name('order.confirmed')->middleware('auth');


// Route::middleware(['auth'])->group(function () {
//
 Route::get('admin-console', function () {
     return view('admin.dashboard');
 })->middleware(['auth', 'role:admin'])->name('admin.dashboard');
//
 Route::middleware(['auth', 'role:admin'])->group(function () {
    Route::prefix('admin')->group(function () {
        Route::resource('contact', 'Backend\ContactController');
        Route::resource('user', 'Backend\UserController');
        Route::resource('category', 'Backend\CategoryController');
        Route::resource('space', 'Backend\SpaceController');
        Route::resource('itemtype', 'Backend\ItemtypeController');
        Route::resource('location', 'Backend\LocationController');
        Route::resource('item', 'Backend\ItemController');
        Route::resource('time_slot', 'Backend\TimeSlotController');
        Route::resource('description', 'Backend\DescriptionController');
        Route::resource('location_description', 'Backend\LocationDescriptionController');
        Route::resource('issue', 'Backend\IssuesController');
        Route::resource('issue_mapping', 'Backend\Issue_MappingsController');
        Route::resource('immediate_issue', 'Backend\ImmediateIssueController');
        Route::resource('cart', 'Backend\CartController');
        Route::get('cart/{order_id}/{status}', 'Backend\CartController@status');
        Route::resource('payment_type', 'Backend\PaymentTypeController');
        Route::resource('item_mapping', 'Backend\Item_MappingsController');
        Route::resource('services', 'Backend\ServiceController');
        Route::get('services/table/data', 'Backend\ServiceController@tableData')->name('services.table');
        Route::post('order/{cart}/status', 'HomeController@changeStatus')->name('order.status');
        Route::get('config', 'Backend\AppConfigController@index')->name('app.config');
        Route::post('config', 'Backend\AppConfigController@update')->name('app.config');

    });
 });
Route::get('activity','HomeController@activity')->name('user.activity');
Route::get('category/{category}', 'Backend\CategoryController@show');
Route::get('services/{service}', 'Backend\ServiceController@show');
Route::get('item-type/{item_type}', 'Backend\ItemtypeController@show');
Route::get('item/{item}', 'Backend\ItemController@show');
Route::get('item-mapping/{item}', 'Backend\Item_MappingsController@show');
Route::get('get/timeslot/{day}', 'HomeController@getTimeSlot')->name('order.getTime');

Route::get('debug', 'DebugController@index');
Route::post('contact/us', 'ContactController@contactAdd')->name('contact.data');
Route::post('order/{cart}/cancel', 'HomeController@cancelOrder')->name('order.cancel');

app/Space.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Space extends Model
{
     protected $fillable = [
   		'id',
        'name',
        ];
    //
}

app/Http/Controllers/Backend/SpaceController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Space;
use Illuminate\Http\Request;

class SpaceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $spaces = Space::all();
        return view('admin.spaces.index', compact('spaces'));
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('admin.spaces.create');
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $space= new Space([
            'name' => $request->get('name'),
            ]);

        $space->save();
        return redirect(route('space.index'))->with(['success' => true, 'success.message' => 'Space Created Successfully']);
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Space  $space
     * @return \Illuminate\Http\Response
     */
    public function show(Space $space)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Space  $space
     * @return \Illuminate\Http\Response
     */
    public function edit(Space $space)
    {
         return view('admin.spaces.edit', compact('space'));
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Space  $space
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Space $space)
    {
        
        $space->name = $request->name;
        $space->save();
       
        return redirect(route('space.index'))->with(['success' => true, 'success.message' => 'space Updated Successfully']);

        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Space  $space
     * @return \Illuminate\Http\Response
     */
    public function destroy(Space $space)
    {
        $space->delete();
        return 'true';
        //
    }
}

resources/views/admin/spaces/create.blade.php
@extends('layouts.backend.master')
@section('content')

        <div class="content-wrapper">
        <!-- Default form contact -->

        @if(count($errors) >0)
        <div class="alert alert-danger">
        <ul>
        @foreach($errors->all() as $error)

        <li>{{$error}}</li>
        @endforeach

        </ul>
        </div>
        @endif
        @if(\Session::has('success'))
    <div class="alert alert-success">
    <p>{{\Session::get('success')}}</p>
    </div>
        @endif
                    <div class="card">

<form class="text-center border border-light p-5" action="{{route('space.store')}}" method="post" id="spaceAdd">

     {{csrf_field()}}
   <div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label>Spaces Name</label>
            <input type="text" name="name" id="defaultContactFormName" class="form-control" placeholder="Spaces Name">
        </div>
    </div>

</div>
    <!-- Copy -->


    <!-- Send button -->
    <div class="col-md-6">
    <button  class="btn btn-info btn-block" type="submit">Save</button>
</div>
</form>
<!-- Default form contact -->
        </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css">


@endsection
@section('script')
<script>
        $("#spaceAdd").validate({
            rules: {
                name: {
                    required: true,
                    // minlength: 5
                },

            },
            messages: {
                name: {
                    required: "Please enter a name",
                    // minlength: "Item name must consist of at least 5 characters"
                },

            },
            errorPlacement: function (label, element) {
                label.addClass('mt-2 text-danger');
                label.insertAfter(element);
            },
            highlight: function (element, errorClass) {
                $(element).parent().addClass('has-danger')
                $(element).addClass('form-control-danger')
            }
        });
    </script>
<script src="{{ asset('admin/js/data-table.js')}}"></script>
@endsection

resources/views/admin/spaces/edit.blade.php
@extends('layouts.backend.master')
@section('content')

        <div class="content-wrapper">
        <!-- Default form contact -->

        @if(count($errors) >0)
        <div class="alert alert-danger">
        <ul>
        @foreach($errors->all() as $error)

        <li>{{$error}}</li>
        @endforeach

        </ul>
        </div>
        @endif
        @if(\Session::has('success'))
    <div class="alert alert-success">
    <p>{{\Session::get('success')}}</p>
    </div>
        @endif
                    <div class="card">

 {!! Form::model($space, ['route' => ['space.update', $space->id], 'method' => 'PATCH']) !!}

     {{csrf_field()}}
   <div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label>Spaces Name</label>
            <input type="text" name="name" id="defaultContactFormName" class="form-control" placeholder="Spaces Name" value="{{$space->name}}">
        </div>
    </div>

</div>
    <!-- Copy -->


    <!-- Send button -->
    <div class="col-md-6">
    <button  class="btn btn-info btn-block" type="submit">Update</button>
</div>
 {!! Form::close() !!}
<!-- Default form contact -->
        </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css">


@endsection
@section('script')
<script>
        $("#spaceAdd").validate({
            rules: {
                name: {
                    required: true,
                    // minlength: 5
                },

            },
            messages: {
                name: {
                    required: "Please enter a name",
                    // minlength: "Item name must consist of at least 5 characters"
                },

            },
            errorPlacement: function (label, element) {
                label.addClass('mt-2 text-danger');
                label.insertAfter(element);
            },
            highlight: function (element, errorClass) {
                $(element).parent().addClass('has-danger')
                $(element).addClass('form-control-danger')
            }
        });
    </script>
<script src="{{ asset('admin/js/data-table.js')}}"></script>
@endsection

resources/views/admin/spaces/index.blade.php
@extends('layouts.backend.master')
@section('content')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.6.9/sweetalert2.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.6.9/sweetalert2.min.js"></script>

        <div class="content-wrapper">
          <div class="page-header">
            <h3 class="page-title">
            Spaces
            </h3>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Home </a></li>
                <li class="breadcrumb-item active" aria-current="page"> Users</li>
              </ol>
            </nav>
          </div>
          <div class="card">
            <div class="card-body">

              <h4 class="card-title">Spaces Details</h4>
                <div class="row">
                <div class="col-12">
                  <div class="table-responsive">
                    <table id="order-listing" class="table">
                      <thead>
                        <tr>
                            <th>#</th>
                              <th>Space Name</th>
                               <th>Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach ($spaces as $key => $space)
                                    <tr>
                                        <td>{{++$key}}</td>
                                        <td>{{$space->name}}</td>


                                         <td>
                                            <a href="{{route('space.edit',[$space->id])}}"><i class="fas fa-pencil-alt btn-icon-append "> </i></a>
                                            <a href="" data-id="{{$space->id}}" class="button delete-confirm">
                                                <i style="color: #e52d27;" class="remove ml-2 fa fa-times-circle"> </i>
                                            </a>
                                        </td>
                                    </tr>
                                    @endforeach
                      </tbody>
                    </table>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>


<a href="{{ route('space.create')}}">
        <div id="settings-trigger"><i class="fas fa-plus-circle fa-10x"></i></div>
    </a>
@endsection
@section('script')
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script>
$('.delete-confirm').on('click', function (e) {
    event.preventDefault();
     var id = $(this).data('id');
    const url = $(this).attr('href');
    // alert(id);
    swal({
        title: 'Are you sure?',
        text: 'This record and it`s details will be permanantly deleted!',
        icon: 'warning',
        buttons: ["Cancel", "Yes!"],
    }).then(function(value) {
        if (value) {
           // window.location.href = url;
            $.ajaxSetup({
                        headers: {
                            'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                        }
                    });
                $.ajax({
                        type: "delete",
                        url: '/admin/space/' + id,
                        data: {
                            id: id
                        },
                        success: function (success) {
                            if (success) {
                                swal(
                                    'Deleted!',
                                    'Your record has been deleted.',
                                    'success'
                                );
                                location.reload();
                            } else {
                                let msg = value.message;
                                console.log('msg');
                            }
                        }
                    });
        }
    });
});
</script>
<script src="{{ asset('admin/js/data-table.js')}}"></script>
@endsection