routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/', 'HomeController');
Route::get('plumbing', function () {
    return view('plumbing');
});

Route::get('service/{service?}', 'HomeController@SelectService')->name('service.select');
Route::get('cart/{category}', 'HomeController@category');

Route::get('plumbing4/{service}/{category}', 'HomeController@service');
Route::get('plumbing5/{item_mapping_id}', 'HomeController@itemtype');
Route::get('plumbing6/{itemTypeId}', 'HomeController@item');
//Route::get('summary/{cart_id}', 'HomeController@summary')->name('order.summary');
//Route::get('confirm/{cart_id}', 'HomeController@confirm')->name('order.confirm');
Route::get('account', 'HomeController@account');
Route::get('security', 'HomeController@security');
Route::resource('accountupdate', 'AccountController');





Route::get('/logout', 'Auth\LoginController@logout');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::post('/proceed', 'HomeController@proceedTransaction')->name('proceed.transaction');


Route::get('user/data/{cart}', 'HomeController@OrderAddress')->name('cart.user')->middleware('auth');
Route::post('user/data', 'HomeController@submitOrderAddress')->name('address.submit')->middleware('auth');
Route::get('summary/{cart}', 'HomeController@orderSummary')->name('order.summary')->middleware('auth');
Route::post('confirm', 'HomeController@confirmOrder')->name('order.confirm')->middleware('auth');
Route::post('confirm/{cart}', 'HomeController@submitConfirmOrder')->name('order.confirmed')->middleware('auth');


// Route::middleware(['auth'])->group(function () {
//
 Route::get('admin-console', function () {
     return view('admin.dashboard');
 })->middleware(['auth', 'role:admin'])->name('admin.dashboard');
//
 Route::middleware(['auth', 'role:admin'])->group(function () {
    Route::prefix('admin')->group(function () {
        Route::resource('contact', 'Backend\ContactController');
        Route::resource('user', 'Backend\UserController');
        Route::resource('category', 'Backend\CategoryController');
        Route::resource('space', 'Backend\SpaceController');
        Route::resource('itemtype', 'Backend\ItemtypeController');
        Route::resource('location', 'Backend\LocationController');
        Route::resource('item', 'Backend\ItemController');
        Route::resource('time_slot', 'Backend\TimeSlotController');
        Route::resource('description', 'Backend\DescriptionController');
        Route::resource('location_description', 'Backend\LocationDescriptionController');
        Route::resource('issue', 'Backend\IssuesController');
        Route::resource('issue_mapping', 'Backend\Issue_MappingsController');
        Route::resource('immediate_issue', 'Backend\ImmediateIssueController');
        Route::resource('cart', 'Backend\CartController');
        Route::get('cart/{order_id}/{status}', 'Backend\CartController@status');
        Route::resource('payment_type', 'Backend\PaymentTypeController');
        Route::resource('item_mapping', 'Backend\Item_MappingsController');
        Route::resource('services', 'Backend\ServiceController');
        Route::get('services/table/data', 'Backend\ServiceController@tableData')->name('services.table');
        Route::post('order/{cart}/status', 'HomeController@changeStatus')->name('order.status');
        Route::get('config', 'Backend\AppConfigController@index')->name('app.config');
        Route::post('config', 'Backend\AppConfigController@update')->name('app.config');

    });
 });
Route::get('activity','HomeController@activity')->name('user.activity');
Route::get('category/{category}', 'Backend\CategoryController@show');
Route::get('services/{service}', 'Backend\ServiceController@show');
Route::get('item-type/{item_type}', 'Backend\ItemtypeController@show');
Route::get('item/{item}', 'Backend\ItemController@show');
Route::get('item-mapping/{item}', 'Backend\Item_MappingsController@show');
Route::get('get/timeslot/{day}', 'HomeController@getTimeSlot')->name('order.getTime');

Route::get('debug', 'DebugController@index');
Route::post('contact/us', 'ContactController@contactAdd')->name('contact.data');
Route::post('order/{cart}/cancel', 'HomeController@cancelOrder')->name('order.cancel');

app/Item_Mapping.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Item_Mapping extends Model
{
    use SoftDeletes;
    protected $table = 'item_mappings';
    protected $fillable = [
        'id',
        'category_id',
        'service_id',
        'itemtype_id',
        'status',
        'price'

    ];

    protected static function boot()
    {
        parent::boot();
        static::addGlobalScope('status', function (Builder $builder) {
            $builder->where('status', '=', 1);
        });
    }

    public function item()
    {
        return $this->belongsTo(Item::class)->withoutGlobalScopes(['status']);
    }

    public function category()
    {
        return $this->belongsTo(Category::class)->withoutGlobalScopes(['status']);
    }

    public function service()
    {
        return $this->belongsTo(Service::class)->withoutGlobalScopes(['status']);
    }

    public function itemtype()
    {
        return $this->belongsTo(Itemtype::class)->withoutGlobalScopes(['status']);
    }
    //
}

app/Http/Controllers/Backend/Item_MappingsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;

use App\Category;
use App\IssueMapping;
use App\Itemtype;
use App\Service;
use App\Item_Mapping;
use Illuminate\Http\Request;

class Item_MappingsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $data = Item_Mapping::withoutGlobalScopes(['status'])->get();
        return view('admin.item_mappings.index', compact('data'));
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $itemstype = Itemtype::pluck('itemtypeid', 'id');
        $category = Category::pluck('category_name', 'id');
        $service = Service::pluck('name', 'id');


        return view('admin.item_mappings.create', compact('category', 'service', 'itemstype'));
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (!$request->issue_id == 0) {
            $current = IssueMapping::whereItemMappingId($request->item_mapping_id)->whereIssueId(0)->first();
            if (!empty($current) && $current->count() > 0) {
                return redirect(route('item_mapping.index'))->with(['error' => true, 'error.title' =>'Sorry !','error.message' => 'Cant Create Item mapping']);
            }
        } else {
            $current = IssueMapping::whereItemMappingId($request->item_mapping_id)->where('issue_id', '<>', 0)->first();
            if (!empty($current) && $current->count() > 0) {
                return redirect(route('item_mapping.index'))->with(['error' => true,'error.title' =>'Sorry !', 'error.message' => 'Cant Create Item mapping']);
            }
        }
        $item_mapping = Item_Mapping::create($request->all());
        return redirect(route('item_mapping.index'))->with(['success' => true, 'success.message' => 'Item Mapping Created Successfully']);

    }

    /**
     * Display the specified resource.
     *
     * @param \App\Item_Mapping $item_Mapping
     * @return \Illuminate\Http\Response
     */
    public function show(Item_Mapping $item)
    {
        return Item_Mapping::with('service')->where('id', '=', $item->id)->first();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Item_Mapping $item_Mapping
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request)
    {
        $item_mapping_id = $request->item_mapping;
        $item_mapping = Item_Mapping::withoutGlobalScopes(['status'])->whereId($item_mapping_id)->first();
        $category = Category::pluck('category_name', 'id');
        $service = Service::pluck('name', 'id');
        $itemstype = Itemtype::pluck('itemtypeid', 'id');

        return view('admin.item_mappings.edit', compact('item_mapping', 'category', 'service', 'itemstype'));
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Item_Mapping $item_Mapping
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $item_mapping_id = $request->item_mapping;
        $item_mapping = Item_Mapping::withoutGlobalScopes(['status'])->whereId($item_mapping_id)->first();
        $item_mapping->category_id = $request->category_id;
        $item_mapping->service_id = $request->service_id;
        $item_mapping->itemtype_id = $request->itemtype_id;
        $item_mapping->price = $request->price;
        $item_mapping->status = $request->status;

        $item_mapping->save();

        return redirect(route('item_mapping.index'))->with(['success' => true, 'success.message' => 'Item Mapping Updated Successfully']);
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Item_Mapping $item_Mapping
     * @return \Illuminate\Http\Response
     */
    public function destroy(Item_Mapping $item_mapping)
    {
        $issue = IssueMapping::whereItemMappingId($item_mapping->id)->get();
        if (!empty($issue) && $issue->count()>0){
            return 'false';
        }
        $item_mapping->delete();
        return 'true';
        //
    }
}

resources/views/admin/item_mappings/create.blade.php
@extends('layouts.backend.master')

@section('content')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
               Item Mapping Create
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/home">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{route('item_mapping.index')}}">Item Mapping</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Create</li>
                </ol>
            </nav>
        </div>
        <div class="card">
            <div class="card-body">
                {!! Form::open(['route' => 'item_mapping.store', 'method' => 'post','id'=>'createForm']) !!}
                @include('admin.item_mappings.form')
                <input class="btn btn-primary" type="submit" value="Submit">
                {!! Form::close() !!}
            </div>
        </div>
    </div>

@endsection

@section('script')
    <script>
        $("#createForm").validate({
            rules: {
                time_slots_id: {
                    required: true,
                },
                
            },
            errorPlacement: function (label, element) {
                label.addClass('mt-2 text-danger');
                label.insertAfter(element);
            },
            highlight: function (element, errorClass) {
                $(element).parent().addClass('has-danger');
                $(element).addClass('form-control-danger');
            }
        });
    </script>
@endsection

resources/views/admin/item_mappings/edit.blade.php
@extends('layouts.backend.master')

@section('content')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                Item Mapping Edit
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/home">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{route('item_mapping.index')}}">Item Mapping</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Edit </li>
                </ol>
            </nav>
        </div>
        <div class="card">
            <div class="card-body">

               {!! Form::model($item_mapping, ['route' => ['item_mapping.update', $item_mapping->id], 'method' => 'PATCH','files'=>true]) !!}
                @include('admin/item_mappings.form')
                <input class="btn btn-primary" type="submit" value="Update">
                {!! Form::close() !!}
            </div>
        </div>
    </div>

@endsection

@section('script')
    <script>
        $("#itemEdit").validate({
            rules: {
                description_id: {
                    required: true,
                    minlength: 5
                },
                location_id: {
                    number: true,
                    required: true,
                    min: 0,
                },

            },
            messages: {
                name: {
                    required: "Please Select a description id",
                    //minlength: "Item name must consist of at least 5 characters"
                },
                price: {
                    required: "Please Select the location id",
                    //min: "Price must be greater than 0"
                }
            },
            errorPlacement: function (label, element) {
                label.addClass('mt-2 text-danger');
                label.insertAfter(element);
            },
            highlight: function (element, errorClass) {
                $(element).parent().addClass('has-danger')
                $(element).addClass('form-control-danger')
            }
        });
    </script>
@endsection

resources/views/admin/item_mappings/form.blade.php
 <div class="col-md-6">
    <div class="form-check form-group">
        <label>Category</label>
            {!! Form::select('category_id', $category,null, ['class' => 'form-control']) !!}
            <i class="input-helper"></i>
    </div>
</div>

<div class="col-md-6">
    <div class="form-check form-group">
        <label class="">Service</label>
            {!! Form::select('service_id', $service,null, ['class' => 'form-control']) !!}
            <i class="input-helper"></i>
    </div>
</div>
<div class="col-md-6">
    <div class="form-check form-group">
        <label class="">Item Type</label>
            {!! Form::select('itemtype_id', $itemstype,null, ['class' => 'form-control']) !!}
            <i class="input-helper"></i>
    </div>
</div>
 <div class="col-md-6">
     <div class="form-group">
         <label>Price</label>
         {!! Form::text('price', null, ['class' => 'form-control']) !!}
     </div>
 </div>

<div class="col-md-6">
    <div class="form-check form-group">
        <label class="form-check-label">
            {!! Form::checkbox('status', '1', 1,  ['id' => 'is_active','class'=>'form-check-input']) !!}
            Is Active
            <i class="input-helper"></i></label>
    </div>
</div>

resources/views/admin/item_mappings/index.blade.php
@extends('layouts.backend.master')
@section('content')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                Item Mapping
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home </a></li>
                    <li class="breadcrumb-item active" aria-current="page">Item Mapping</li>
                </ol>
            </nav>
        </div>
        <div class="card">
            <div class="card-body">

                <h4 class="card-title" settings-trigger>Item Mapping Details</h4>
                <div class="row">
                    <div class="col-12">
                        <div class="table-responsive">
                            <table id="order-listing" class="table">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Category Name</th>
                                    <th>Service Name</th>
                                    <th>Item Name</th>
                                    <th>Price</th>
                                    <th>Status</th>

                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($data as $key => $item_mapping)
                                    <tr>
                                        <td>{{++$key}}</td>
                                        <td>{{$item_mapping->category->category_name}}</td>
                                        <td>{{$item_mapping->service->name}}</td>
                                        <td>{{$item_mapping->itemtype->itemtypeid}}</td>
                                        <td>{{number_format($item_mapping->price,2)}}</td>
                                        @if($item_mapping->status==1)
                                            <td>
                                                <button class="btn btn-sm btn-success">Active</button>
                                            </td>
                                        @else
                                            <td>
                                               <button class="btn btn-sm btn-warning">Deactive</button>
                                            </td>
                                        @endif


                                        <td>
                                            <a href="{{route('item_mapping.edit',[$item_mapping->id])}}"><i
                                                    class="fas fa-pencil-alt btn-icon-append "> </i></a>
                                            <a href="" data-id="{{$item_mapping->id}}" class="button delete-confirm">
                                                <i style="color: #e52d27;" class="remove ml-2 fa fa-times-circle"> </i>
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <a href="{{ route('item_mapping.create')}}">
        <div id="settings-trigger"><i class="fas fa-plus-circle fa-10x"></i></div>
    </a>
@endsection
@section('script')
    <script>
        $('.delete-confirm').on('click', function (e) {
            event.preventDefault();
            var id = $(this).data('id');
            const url = $(this).attr('href');
            // alert(id);
            swal({
                title: 'Are you sure?',
                text: 'This record and it`s details will be permanantly deleted!',
                icon: 'warning',
                buttons: ["Cancel", "Yes!"],
            }).then(function (value) {
                if (value) {
                    // window.location.href = url;
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                        }
                    });
                    $.ajax({
                        type: "delete",
                        url: '/admin/item_mapping/' + id,
                        data: {
                            id: id
                        },
                        success: function (success) {
                            if (success=='true') {
                                swal(
                                    'Deleted!',
                                    'Your record has been deleted.',
                                    'success'
                                );
                                location.reload();
                            } else {
                                swal(
                                    'Sorry!',
                                    'Your record has dependencies.',
                                    'warning'
                                );
                            }
                        }
                    });
                }
            });
        });
    </script>
@endsection