routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/', 'HomeController');
Route::get('plumbing', function () {
    return view('plumbing');
});

Route::get('service/{service?}', 'HomeController@SelectService')->name('service.select');
Route::get('cart/{category}', 'HomeController@category');

Route::get('plumbing4/{service}/{category}', 'HomeController@service');
Route::get('plumbing5/{item_mapping_id}', 'HomeController@itemtype');
Route::get('plumbing6/{itemTypeId}', 'HomeController@item');
//Route::get('summary/{cart_id}', 'HomeController@summary')->name('order.summary');
//Route::get('confirm/{cart_id}', 'HomeController@confirm')->name('order.confirm');
Route::get('account', 'HomeController@account');
Route::get('security', 'HomeController@security');
Route::resource('accountupdate', 'AccountController');





Route::get('/logout', 'Auth\LoginController@logout');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::post('/proceed', 'HomeController@proceedTransaction')->name('proceed.transaction');


Route::get('user/data/{cart}', 'HomeController@OrderAddress')->name('cart.user')->middleware('auth');
Route::post('user/data', 'HomeController@submitOrderAddress')->name('address.submit')->middleware('auth');
Route::get('summary/{cart}', 'HomeController@orderSummary')->name('order.summary')->middleware('auth');
Route::post('confirm', 'HomeController@confirmOrder')->name('order.confirm')->middleware('auth');
Route::post('confirm/{cart}', 'HomeController@submitConfirmOrder')->name('order.confirmed')->middleware('auth');


// Route::middleware(['auth'])->group(function () {
//
 Route::get('admin-console', function () {
     return view('admin.dashboard');
 })->middleware(['auth', 'role:admin'])->name('admin.dashboard');
//
 Route::middleware(['auth', 'role:admin'])->group(function () {
    Route::prefix('admin')->group(function () {
        Route::resource('contact', 'Backend\ContactController');
        Route::resource('user', 'Backend\UserController');
        Route::resource('category', 'Backend\CategoryController');
        Route::resource('space', 'Backend\SpaceController');
        Route::resource('itemtype', 'Backend\ItemtypeController');
        Route::resource('location', 'Backend\LocationController');
        Route::resource('item', 'Backend\ItemController');
        Route::resource('time_slot', 'Backend\TimeSlotController');
        Route::resource('description', 'Backend\DescriptionController');
        Route::resource('location_description', 'Backend\LocationDescriptionController');
        Route::resource('issue', 'Backend\IssuesController');
        Route::resource('issue_mapping', 'Backend\Issue_MappingsController');
        Route::resource('immediate_issue', 'Backend\ImmediateIssueController');
        Route::resource('cart', 'Backend\CartController');
        Route::get('cart/{order_id}/{status}', 'Backend\CartController@status');
        Route::resource('payment_type', 'Backend\PaymentTypeController');
        Route::resource('item_mapping', 'Backend\Item_MappingsController');
        Route::resource('services', 'Backend\ServiceController');
        Route::get('services/table/data', 'Backend\ServiceController@tableData')->name('services.table');
        Route::post('order/{cart}/status', 'HomeController@changeStatus')->name('order.status');
        Route::get('config', 'Backend\AppConfigController@index')->name('app.config');
        Route::post('config', 'Backend\AppConfigController@update')->name('app.config');

    });
 });
Route::get('activity','HomeController@activity')->name('user.activity');
Route::get('category/{category}', 'Backend\CategoryController@show');
Route::get('services/{service}', 'Backend\ServiceController@show');
Route::get('item-type/{item_type}', 'Backend\ItemtypeController@show');
Route::get('item/{item}', 'Backend\ItemController@show');
Route::get('item-mapping/{item}', 'Backend\Item_MappingsController@show');
Route::get('get/timeslot/{day}', 'HomeController@getTimeSlot')->name('order.getTime');

Route::get('debug', 'DebugController@index');
Route::post('contact/us', 'ContactController@contactAdd')->name('contact.data');
Route::post('order/{cart}/cancel', 'HomeController@cancelOrder')->name('order.cancel');

resources/views/admin/itemstype/create.blade.php
@extends('layouts.backend.master')
@section('content')

    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
               Item Type Create
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/home">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{route('itemtype.index')}}">Item Type</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Create</li>
                </ol>
            </nav>
        </div>
        <div class="card">
            <div class="card-body">

                <form class="border border-light p-5" action="{{route('itemtype.store')}}" method="post"
                      id="spaceAdd">

                    {{csrf_field()}}
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>ItemTypes Id</label>
                            <input type="text" name="itemtypeid" id="defaultContactFormName" class="form-control"
                                   placeholder="Item Type Id">
                        </div>
                    </div>


                    <div class="col-md-6">
                        <button class="btn btn-primary" type="submit">Save Item Type</button>
                    </div>
                </form>
                <!-- Default form contact -->
            </div>
        </div>
    </div>

@endsection
@section('script')
    <script>
        $("#spaceAdd").validate({
            rules: {
                itemtypeid: {
                    required: true,
                    // minlength: 5
                },

            },
            messages: {
                itemtypeid: {
                    required: "Please enter Item Type Id",
                    // minlength: "Item name must consist of at least 5 characters"
                },

            },
            errorPlacement: function (label, element) {
                label.addClass('mt-2 text-danger');
                label.insertAfter(element);
            },
            highlight: function (element, errorClass) {
                $(element).parent().addClass('has-danger')
                $(element).addClass('form-control-danger')
            }
        });
    </script>
@endsection

resources/views/admin/itemstype/edit.blade.php
@extends('layouts.backend.master')
@section('content')

    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                Item Type Edit
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/home">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{route('itemtype.index')}}">Item Type</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Edit</li>
                </ol>
            </nav>
        </div>
        <!-- Default form contact -->

        <div class="card">
            <div class="card-body">

                {!! Form::model($itemtype, ['route' => ['itemtype.update', $itemtype->id], 'method' => 'PATCH']) !!}

                {{csrf_field()}}
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Item Type Id</label>
                            <input type="text" name="itemtypeid" id="defaultContactFormName" class="form-control"
                                   placeholder="Item Type Id" value="{{$itemtype->itemtypeid}}">
                        </div>
                    </div>

                </div>
                <!-- Copy -->


                <!-- Send button -->
                <div class="col-md-6">
                    <button class="btn btn-primary" type="submit">Update Item Type</button>
                </div>
            {!! Form::close() !!}
            <!-- Default form contact -->
            </div>
        </div>
    </div>


@endsection
@section('script')
    <script>
        $("#spaceAdd").validate({
            rules: {
                name: {
                    required: true,
                    // minlength: 5
                },

            },
            messages: {
                name: {
                    required: "Please enter a name",
                    // minlength: "Item name must consist of at least 5 characters"
                },

            },
            errorPlacement: function (label, element) {
                label.addClass('mt-2 text-danger');
                label.insertAfter(element);
            },
            highlight: function (element, errorClass) {
                $(element).parent().addClass('has-danger')
                $(element).addClass('form-control-danger')
            }
        });
    </script>
@endsection

resources/views/admin/itemstype/index.blade.php
@extends('layouts.backend.master')
@section('content')
     <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                Item Type
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home </a></li>
                    <li class="breadcrumb-item active" aria-current="page"> Item Type</li>
                </ol>
            </nav>
        </div>
        <div class="card">
            <div class="card-body">

                <h4 class="card-title">Item Type List</h4>
                <div class="row">
                    <div class="col-12">
                        <div class="table-responsive">
                            <table id="order-listing" class="table">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Items Type</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($itemstype as $key => $itemtype)
                                    <tr>
                                        <td>{{++$key}}</td>
                                        <td>{{$itemtype->itemtypeid}}</td>


                                        <td>
                                            <a href="{{route('itemtype.edit',[$itemtype->id])}}"><i
                                                    class="fas fa-pencil-alt btn-icon-append "> </i></a>
                                            <a href="" data-id="{{$itemtype->id}}" class="button delete-confirm">
                                                <i style="color: #e52d27;" class="remove ml-2 fa fa-times-circle"> </i>
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <a href="{{ route('itemtype.create')}}">
        <div id="settings-trigger"><i class="fas fa-plus-circle fa-10x"></i></div>
    </a>
@endsection
@section('script')
     <script>
        $('.delete-confirm').on('click', function (e) {
            event.preventDefault();
            var id = $(this).data('id');
            const url = $(this).attr('href');
            // alert(id);
            swal({
                title: 'Are you sure?',
                text: 'This record and it`s details will be permanently deleted!',
                icon: 'warning',
                buttons: ["Cancel", "Yes!"],
            }).then(function (value) {
                if (value) {
                    // window.location.href = url;
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                        }
                    });
                    $.ajax({
                        type: "delete",
                        url: '/admin/itemtype/' + id,
                        data: {
                            id: id
                        },
                        success: function (success) {
                            if (success=='true') {
                                swal(
                                    'Deleted!',
                                    'Your record has been deleted.',
                                    'success'
                                );
                                location.reload();
                            } else {
                                swal(
                                    'Sorry!',
                                    'Your record has dependencies',
                                    'warning'
                                );
                            }
                        }
                    });
                }
            });
        });
    </script>
@endsection