routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/', 'HomeController');
Route::get('plumbing', function () {
    return view('plumbing');
});

Route::get('service/{service?}', 'HomeController@SelectService')->name('service.select');
Route::get('cart/{category}', 'HomeController@category');

Route::get('plumbing4/{service}/{category}', 'HomeController@service');
Route::get('plumbing5/{item_mapping_id}', 'HomeController@itemtype');
Route::get('plumbing6/{itemTypeId}', 'HomeController@item');
//Route::get('summary/{cart_id}', 'HomeController@summary')->name('order.summary');
//Route::get('confirm/{cart_id}', 'HomeController@confirm')->name('order.confirm');
Route::get('account', 'HomeController@account');
Route::get('security', 'HomeController@security');
Route::resource('accountupdate', 'AccountController');





Route::get('/logout', 'Auth\LoginController@logout');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::post('/proceed', 'HomeController@proceedTransaction')->name('proceed.transaction');


Route::get('user/data/{cart}', 'HomeController@OrderAddress')->name('cart.user')->middleware('auth');
Route::post('user/data', 'HomeController@submitOrderAddress')->name('address.submit')->middleware('auth');
Route::get('summary/{cart}', 'HomeController@orderSummary')->name('order.summary')->middleware('auth');
Route::post('confirm', 'HomeController@confirmOrder')->name('order.confirm')->middleware('auth');
Route::post('confirm/{cart}', 'HomeController@submitConfirmOrder')->name('order.confirmed')->middleware('auth');


// Route::middleware(['auth'])->group(function () {
//
 Route::get('admin-console', function () {
     return view('admin.dashboard');
 })->middleware(['auth', 'role:admin'])->name('admin.dashboard');
//
 Route::middleware(['auth', 'role:admin'])->group(function () {
    Route::prefix('admin')->group(function () {
        Route::resource('contact', 'Backend\ContactController');
        Route::resource('user', 'Backend\UserController');
        Route::resource('category', 'Backend\CategoryController');
        Route::resource('space', 'Backend\SpaceController');
        Route::resource('itemtype', 'Backend\ItemtypeController');
        Route::resource('location', 'Backend\LocationController');
        Route::resource('item', 'Backend\ItemController');
        Route::resource('time_slot', 'Backend\TimeSlotController');
        Route::resource('description', 'Backend\DescriptionController');
        Route::resource('location_description', 'Backend\LocationDescriptionController');
        Route::resource('issue', 'Backend\IssuesController');
        Route::resource('issue_mapping', 'Backend\Issue_MappingsController');
        Route::resource('immediate_issue', 'Backend\ImmediateIssueController');
        Route::resource('cart', 'Backend\CartController');
        Route::get('cart/{order_id}/{status}', 'Backend\CartController@status');
        Route::resource('payment_type', 'Backend\PaymentTypeController');
        Route::resource('item_mapping', 'Backend\Item_MappingsController');
        Route::resource('services', 'Backend\ServiceController');
        Route::get('services/table/data', 'Backend\ServiceController@tableData')->name('services.table');
        Route::post('order/{cart}/status', 'HomeController@changeStatus')->name('order.status');
        Route::get('config', 'Backend\AppConfigController@index')->name('app.config');
        Route::post('config', 'Backend\AppConfigController@update')->name('app.config');

    });
 });
Route::get('activity','HomeController@activity')->name('user.activity');
Route::get('category/{category}', 'Backend\CategoryController@show');
Route::get('services/{service}', 'Backend\ServiceController@show');
Route::get('item-type/{item_type}', 'Backend\ItemtypeController@show');
Route::get('item/{item}', 'Backend\ItemController@show');
Route::get('item-mapping/{item}', 'Backend\Item_MappingsController@show');
Route::get('get/timeslot/{day}', 'HomeController@getTimeSlot')->name('order.getTime');

Route::get('debug', 'DebugController@index');
Route::post('contact/us', 'ContactController@contactAdd')->name('contact.data');
Route::post('order/{cart}/cancel', 'HomeController@cancelOrder')->name('order.cancel');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;
    protected $fillable = [
        'category_id',
        'category_name',
        'is_active',
        'category_image',
        'description'
    ];

    public static function boot()
    {
        parent::boot();

        static::addGlobalScope('status', function (Builder $builder) {
            $builder->where('is_active', '=', 1);
        });
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Item_Mapping;
use DemeterChain\C;
use Illuminate\Http\Request;
use App\Category;
use Illuminate\Support\Facades\File;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::withoutGlobalScopes(['status'])->get();
        return view('admin.categories.index', compact('categories'));
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'category_id' => ['required', 'unique:categories', 'max:191'],
            'category_name' => ['required','unique:categories','max:191'],
            'category_image' => ['required', 'dimensions:width=512,height=512'],
        ]);

        $filename = null;
        if (!empty($request->file('category_image'))) {
            $image = $request->file('category_image');
            $destinationPath = 'upload/frontEnd/icon/';
            $filename = $image->getClientOriginalName();
            $image->move($destinationPath, $filename);
        }

        $category = new Category();
        $category->category_id = $request->category_id;
        $category->category_name = $request->category_name;
        $category->is_active = $request->is_active;
        $category->category_image = $filename;
        $category->save();

        return redirect(route('category.index'))->with(['success' => true, 'success.message' => 'Category Created Successfully']);
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Category $category
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request,$id)
    {
        $category = Category::withoutGlobalScopes(['status'])->whereId($id)->first();
        return $category;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request,$id)
    {
        $category = Category::withoutGlobalScopes(['status'])->whereId($id)->first();
        return view('admin.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Category $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::withoutGlobalScopes(['status'])->whereId($id)->first();

        $validatedData = $request->validate([
            'category_id' => ['required', 'unique:categories,category_id,'.$category->id, 'max:191'],
            'category_name' => ['required','unique:categories,category_name,'.$category->id,'max:191'],
            'category_image' => ['dimensions:width=512,height=512'],
        ]);

        $category->category_id = $request->category_id;
        $category->category_name = $request->category_name;
        $category->is_active = $request->is_active;

        $file = $request->file('category_image');

        if (!empty($file)) {
            $destinationPath = 'upload/frontEnd/icon/';
            File::delete($destinationPath . $category->category_image);//delete current image from storage
            $filename = $file->getClientOriginalName();
            $file->move($destinationPath, $filename);
            $category->category_image = $filename;
        }

        $category->save();
        return redirect(route('category.index'))->with(['success' => true, 'success.message' => 'Item Updated Successfully']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Category $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request,$id)
    {
        $category = Category::withoutGlobalScopes(['status'])->whereId($id)->first();
        $mapping = Item_Mapping::whereCategoryId($category->id)->first();
        if (!empty($mapping) && $mapping->count() > 0) {
            return 'false';
        }
        $category->delete();
        return 'true';
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.backend.master')
@section('content')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                Category Create
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/home">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{route('category.index')}}">Categories</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Create</li>
                </ol>
            </nav>
        </div>
        <div class="card">
            <div class="card-body">
            {!! Form::open(['route' => 'category.store', 'method' => 'post','id'=>'createForm','files'=>true ]) !!}

            <!-- <form class="text-center border border-light p-5" action="{{route('category.store')}}" method="post" id="categoryAdd"> -->

                {{csrf_field()}}

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Category Id</label>
                            <input type="text" name="category_id" id="defaultContactFormName" class="form-control"
                                   placeholder="Category Id">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Category Name</label>
                            <input type="text" name="category_name" id="defaultContactFormEmail"
                                   class="form-control mb-4"
                                   placeholder="Category Name">
                        </div>

                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-check form-group">
                            <label>Image(512px * 512px)</label>
                            {!! Form::file('category_image',['class' => 'form-control']) !!}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Status</label>
                            <select class="browser-default custom-select mb-4" name="is_active">
                                <option value="" disabled>Choose option</option>
                                <option value="1">Enabled</option>
                                <option value="2">Disabled</option>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <button class="btn btn-primary" type="submit">Save Category</button>
                </div>
                {!! Form::close() !!}
            </div>
            <!-- Default form contact -->
        </div>
    </div>
@endsection
@section('script')
    <script>
        $("#categoryAdd").validate({
            rules: {
                category_id: {
                    required: true,
                },
                category_name: {
                    required: true,
                },
                is_active: {
                    required: true,
                },
                category_image: {
                    required: true,
                },
            },
            messages: {
                category_id: {
                    required: "Please enter a category Id",
                },
                category_name: {
                    required: "Please enter the category name",
                }
            },
            errorPlacement: function (label, element) {
                label.addClass('mt-2 text-danger');
                label.insertAfter(element);
            },
            highlight: function (element, errorClass) {
                $(element).parent().addClass('has-danger')
                $(element).addClass('form-control-danger')
            }
        });
    </script>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.backend.master')
@section('content')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                Category Edit
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/home">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{route('category.index')}}">Categories</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Edit</li>
                </ol>
            </nav>
        </div>
        <div class="card">
            <div class="card-body">
            {!! Form::model($category, ['route' => ['category.update', $category->id],'files'=>true, 'method' => 'PATCH']) !!}
            <!-- <form class="text-center border border-light p-5" action="{{route('category.update',$category->id)}}" method="PATCH"> -->

                {{csrf_field()}}
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Category Id</label>
                            <input type="text" name="category_id" id="defaultContactFormName" class="form-control"
                                   placeholder="Category Id" value="{{$category->category_id}}">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Category Name</label>
                            <input type="text" name="category_name" id="defaultContactFormEmail"
                                   class="form-control mb-4" placeholder="Category Name"
                                   value="{{$category->category_name}}">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-check form-group">

                        <label>Image(512px * 512px)</label>
                        @if (!empty($category->category_image))
                            <img id="category_image" width="100px"
                                 src="{{asset('upload/frontEnd/icon/'.$category->category_image)}}" alt=""/>
                        @endif
                        {!! Form::file('category_image',['class' => 'form-control']) !!}

                    </div>
                </div>

                <!-- Copy -->

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Status</label>
                            <select class="browser-default custom-select mb-4" name="is_active">
                                <option value="" disabled>Choose option</option>
                                <option value="1" {{ $category->is_active == 1 ? 'selected' : '' }}>Enabled</option>
                                <option value="2" {{ $category->is_active == 2 ? 'selected' : '' }}>Disabled</option>
                            </select>
                        </div>
                    </div>

                </div>
                <!-- Send button -->
                <div class="col-md-6">
                    <input class="btn btn-primary" type="submit" value="Save">
                </div>
            {!! Form::close() !!}
            <!-- </form> -->
                <!-- Default form contact -->
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script>
        $("#categoryAdd").validate({
            rules: {
                category_id: {
                    required: true,
                },
                category_name: {
                    required: true,
                },
                is_active: {
                    required: true,
                },
                category_image: {
                    required: true,
                },
            },
            messages: {
                category_id: {
                    required: "Please enter a category Id",
                },
                category_name: {
                    required: "Please enter the category name",
                }
            },
            errorPlacement: function (label, element) {
                label.addClass('mt-2 text-danger');
                label.insertAfter(element);
            },
            highlight: function (element, errorClass) {
                $(element).parent().addClass('has-danger')
                $(element).addClass('form-control-danger')
            }
        });
    </script>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.backend.master')
@section('content')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                Categories
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home </a></li>
                    <li class="breadcrumb-item active" aria-current="page"> Categories</li>
                </ol>
            </nav>
        </div>
        <div class="card">
            <div class="card-body">

                <h4 class="card-title">Categories List</h4>
                <div class="row">
                    <div class="col-12">
                        <div class="table-responsive">
                            <table id="order-listing" class="table">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Category ID</th>
                                    <th>Category Name</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($categories as $key => $category)
                                    <tr>
                                        <td>{{++$key}}</td>
                                        <td>{{$category->category_id}}</td>
                                        <td>{{$category->category_name}}</td>
                                        <td>
                                            @if($category->is_active==1)
                                                <button class="btn btn-sm btn-success">Enabled</button>
                                            @else
                                                <button class="btn btn-sm btn-danger">Disabled</button>
                                            @endif
                                        </td>
                                        {{--<td><input class="target" type="button" onclick="myFunction(this)"></td>--}}
                                        <td>
                                            <a href="{{route('category.edit',[$category->id])}}"><i
                                                    class="fas fa-pencil-alt btn-icon-append "> </i></a>
                                            <a href="" data-id="{{$category->id}}" class="button delete-confirm">
                                                <i style="color: #e52d27;"
                                                   class="remove ml-2 fa fa-times-circle"> </i>
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <a href="{{ route('category.create')}}">
        <div id="settings-trigger"><i class="fas fa-plus-circle fa-10x"></i></div>
    </a>
@endsection
@section('script')
    <script>
        $('.delete-confirm').on('click', function (e) {
            event.preventDefault();
            var id = $(this).data('id');
            const url = $(this).attr('href');
            // alert(id);
            swal({
                title: 'Are you sure?',
                text: 'This record and it`s details will be permanently deleted!',
                icon: 'warning',
                buttons: ["Cancel", "Yes!"],
            }).then(function (value) {
                if (value) {
                    // window.location.href = url;
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                        }
                    });
                    $.ajax({
                        type: "delete",
                        url: '/admin/category/' + id,
                        data: {
                            id: id
                        },
                        success: function (success) {
                            if (success == 'true') {
                                swal(
                                    'Deleted!',
                                    'Your record has been deleted.',
                                    'success'
                                );
                                location.reload();
                            } else {
                                swal(
                                    'Sorry!',
                                    'Your record has dependencies.',
                                    'warning'
                                );
                            }
                        }
                    });
                }
            });
        });
    </script>

@endsection